apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: my-pool
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  namespace: kafka
spec:
  roles:
    - controller
  storage:
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    type: jbod
  replicas: 3
