---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Operators
  - kafka-operator.yaml
  - kafka-console-operator.yaml

  # Cluster
  - kafka-namespace.yaml
  - kafka-cluster.yaml
  - kafka-user.yaml
