apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  namespace: kafka
  name: inventory-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  config:
    database.dbname: inventory
    database.hostname: postgres.di.svc.cluster.local
    database.password: debezium
    database.port: 5432
    database.server.name: postgres
    database.user: debezium
    topic.prefix: dbz
    plugin.name: pgoutput
  tasksMax: 1
