apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appNamespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        deployment: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "image-registry.openshift-image-registry.svc:5000/{{ .Values.appNamespace }}/{{ .Values.appName }}:latest"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP

