---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: rhbk
  name: rhbk
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/rhbk
    repoURL: https://github.com/olle-hub/kafka-playground.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
